### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by jerone**
### Changes

*   Development changes:
    *   Update NPM packages.
    *   Introduce EditorConfig for consistent tabs/spaces code styling.
    *   Include `package-lock.json`.
    *   Make type-safe. Force some settings through `tsconfig.json`.
    *   Implement ESLint for consistent code styling.
    *   Add `.gitignore` file.
*   Upgrade VSCode extension template:
    *   Upgrade from package `vscode` to `vscode-test` & `@types/vscode`.
    *   Upgrade `launch.json` & `tasks.json` configurations.
    *   Update VSCode specific properties in `package.json`.
*   Import metadata directly from Clarity.
    *   Clarity is now a dependency.
*   Import descriptions from `src/metadata.json`, when available.
*   Run on every HTML language, including unsaved files.
*   Snippets for all components.
*   Unit tests.

### TODO

*   [x] Improve loading of metadata.
*   [x] Validate existing snippets.
*   [x] Add snippets for new elements.
*   [x] ~Investigate if it's possible to import different versions of Clarity.~
    *   [x] Skipping research for now.
*   [x] Implement ESLint.
*   [ ] Build unit tests.
*   [x] Update readme.
*   [x] Update changelog.
*   [x] Increase version (changelog too).
    *   [x] I creased the semver to major.
    *   [ ] Update the date in the changelog.
*   [ ] Missing LICENSE file.

### Notes

As this is my first introduction with VSCode extension development, excuse my commits. I recommend squashing this PR.

### CODE REVIEW

**Review by agiove — APPROVED** [review]

**Review by agiove — APPROVED** [review]

**Review by agiove — APPROVED** [review]

**Comment by jerone** [comment]
Hi @agiove. Thanks for reviewing! It is still a draft, I want to do a few more things to make it even better. 

I'm doing these things in my spare time. Once all important things are done, I'll mark this PR ready for review.

**Comment by jerone** [comment]
@agiove I think this PR is at a stage where I'm happy with. Would you care to review it?

Two things to consider:

1.  Improve unit tests - the unit tests could probably be improved and extended.
2.  Testing - I only did development testing.

**Comment by jerone** [comment]
I need to read up a little how an VSCode extension is packaged. Not sure if the referenced JSON file is included in the VSIX package.

**Comment by jerone** [comment]
> I need to read up a little how an VSCode extension is packaged. Not sure if the referenced JSON file is included in the VSIX package.

So, yeah, this requires some extra work. The npm modules that are referenced in the extension are excluded from the package. Changing modules from dev to prod seems to work, but creates another issue when packaging:

> This extension consists of 8063 files, out of which 7073 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files   
> by adding them to your .vscodeignore: [https://aka.ms/vscode-vscodeignore](https://aka.ms/vscode-vscodeignore)

Going to look into bundling options...

**Comment by jerone** [comment]
@agiove The tooling is complaining about a missing LICENSE file. Could you provide one that suits your needs for this project. Can be contributed directly to this branch or via PR to my branch.

**Comment by agiove** [comment]
> Could you provide one that suits your needs for this project. Can be contributed directly to this branch or via PR to my branch.

We could use the MIT license.

**Comment by spamguy** [comment]
@jerone Are you still working on this? How can I help?

**Comment by jerone** [comment]
@spamguy I'm not actively developing on it for the moment, for the following reasons (besides time):
1. I couldn't create an working version that compiled correctly.
2. I was searching for a way to get all metadata automatically, instead of maintaining our own version.
3. Clarity roadmap changed and is somewhat unclear. There focus moved to `@cds/core`.

My last stash I've got includes the introduction to webpack to fix point 1 & 2. Dunno what the status is for that.

If you are willing to contribute, feel free to send PR's to [my branch](https://github.com/jerone/clarity-vscode/tree/feature/update) and I'll have a look at it.

I would love to see this upgrade finished.

**Comment by jerone** [comment]
Closing this PR as my focus has been shifted away from Clarity.
I'll keep the branch if anyone is interested in finishing it.

**Pull request closed without merging**
